# Generated by Django 3.2.12 on 2022-06-03 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, default='No Description', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('design_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('designation', models.TextField(blank=True, default='No Description', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=70)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=125)),
                ('mobile', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=15)),
                ('state_of_orgin', models.CharField(max_length=15)),
                ('lga_of_orgin', models.CharField(max_length=15)),
                ('address', models.TextField(default='', max_length=100)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('state_of_residence', models.CharField(max_length=100)),
                ('lga_of_residence', models.CharField(max_length=15)),
                ('emergency', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=10)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('yoruba', 'YORUBA'), ('hausa', 'HAUSA'), ('french', 'FRENCH')], default='english', max_length=10)),
                ('account_no', models.CharField(default='', max_length=10)),
                ('bank', models.CharField(default='', max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('employeetype_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('employeetype', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('employ_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('doe', models.DateTimeField(default=django.utils.timezone.now)),
                ('step', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('gradelevel', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)])),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='dept', to='hrms.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.designation')),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
                ('employee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employeetype')),
            ],
        ),
        migrations.CreateModel(
            name='KPD',
            fields=[
                ('period', models.DateField(choices=[(datetime.date(2022, 6, 1), 'P:6:2022'), (datetime.date(2022, 7, 1), 'P:7:2022'), (datetime.date(2022, 8, 1), 'P:8:2022'), (datetime.date(2022, 9, 1), 'P:9:2022'), (datetime.date(2022, 10, 1), 'P:10:2022'), (datetime.date(2022, 11, 1), 'P:11:2022'), (datetime.date(2022, 12, 1), 'P:12:2022')], max_length=70)),
                ('kpd_id', models.AutoField(primary_key=True, serialize=False)),
                ('kpd', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.department')),
            ],
        ),
        migrations.CreateModel(
            name='KPIScoreRange',
            fields=[
                ('kpisr_id', models.AutoField(primary_key=True, serialize=False)),
                ('kpiscore_range_min', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)])),
                ('kpiscore_range_max', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)])),
                ('kpiscore_remark', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_code', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=70)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.department')),
                ('head_of_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
                ('station_location', models.TextField(default='', max_length=100)),
                ('station_address', models.TextField(default='', max_length=100)),
                ('station_email_address', models.EmailField(max_length=30)),
                ('station_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SMKPD',
            fields=[
                ('smkpd_id', models.AutoField(primary_key=True, serialize=False)),
                ('skpdmonth', models.CharField(blank=True, max_length=50)),
                ('perc_weight', models.IntegerField()),
                ('expected_time_of_delivery', models.CharField(blank=True, max_length=50)),
                ('kpd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.kpd')),
            ],
        ),
        migrations.CreateModel(
            name='SKPD',
            fields=[
                ('skpd_id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.DateField(choices=[(datetime.date(2022, 6, 1), 'P:6:2022'), (datetime.date(2022, 7, 1), 'P:7:2022'), (datetime.date(2022, 8, 1), 'P:8:2022'), (datetime.date(2022, 9, 1), 'P:9:2022'), (datetime.date(2022, 10, 1), 'P:10:2022'), (datetime.date(2022, 11, 1), 'P:11:2022'), (datetime.date(2022, 12, 1), 'P:12:2022')], max_length=70)),
                ('date', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField()),
                ('expected_time_of_delivery', models.CharField(default='', max_length=15)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hrms.employment')),
                ('kpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_kpd', to='hrms.kpd')),
            ],
        ),
        migrations.CreateModel(
            name='SBU_Directorate',
            fields=[
                ('sbu_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('sbu_name', models.CharField(max_length=50)),
                ('sbu_email', models.EmailField(max_length=30)),
                ('director_of_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MKPD',
            fields=[
                ('mkpd_id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.DateField(choices=[(datetime.date(2022, 6, 1), 'P:6:2022'), (datetime.date(2022, 7, 1), 'P:7:2022'), (datetime.date(2022, 8, 1), 'P:8:2022'), (datetime.date(2022, 9, 1), 'P:9:2022'), (datetime.date(2022, 10, 1), 'P:10:2022'), (datetime.date(2022, 11, 1), 'P:11:2022'), (datetime.date(2022, 12, 1), 'P:12:2022')], max_length=70)),
                ('week', models.CharField(blank=True, choices=[('week 1', 'WEEK 1'), ('week 2', 'WEEK 2'), ('week 3', 'WEEK 3'), ('week 4', 'WEEK 4'), ('week 5', 'WEEK 5')], max_length=15, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('time_in', models.CharField(max_length=15, null=True)),
                ('time_out', models.CharField(max_length=15, null=True)),
                ('approved', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employment')),
                ('skpd', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hrms.skpd')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('unapproved', 'UNAPPROVED'), ('decline', 'DECLINED')], default='Not Approved', max_length=15)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='KPIScorePenalty',
            fields=[
                ('kpisp_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_penalty', models.IntegerField(default=0.0)),
                ('paybenchmark', models.CharField(default='No Pay Cut', max_length=100)),
                ('kpiscore_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.kpiscorerange')),
            ],
        ),
        migrations.CreateModel(
            name='KPI_Evalutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(choices=[(datetime.date(2022, 6, 1), 'P:6:2022'), (datetime.date(2022, 7, 1), 'P:7:2022'), (datetime.date(2022, 8, 1), 'P:8:2022'), (datetime.date(2022, 9, 1), 'P:9:2022'), (datetime.date(2022, 10, 1), 'P:10:2022'), (datetime.date(2022, 11, 1), 'P:11:2022'), (datetime.date(2022, 12, 1), 'P:12:2022')], default=datetime.date.today, max_length=70)),
                ('week', models.CharField(blank=True, choices=[('week 1', 'WEEK 1'), ('week 2', 'WEEK 2'), ('week 3', 'WEEK 3'), ('week 4', 'WEEK 4'), ('week 5', 'WEEK 5')], max_length=15, null=True)),
                ('score', models.IntegerField(null=True)),
                ('remark', models.CharField(blank=True, max_length=15, null=True)),
                ('comment', models.CharField(choices=[('excellent', 'EXCELLENT'), ('very good', 'VERY GOOD'), ('good', 'GOOD'), ('satisfactory', 'SATISFACTORY'), ('unsatisfactory', 'UNSATISFACTORY')], default='', max_length=200)),
                ('approved', models.CharField(choices=[('NOT APPROVED', 'NOT APPROVED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='hrms.employment')),
                ('mkpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hrms.mkpd')),
                ('skpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submission', to='hrms.skpd')),
            ],
        ),
        migrations.AddField(
            model_name='kpd',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.sbu_directorate'),
        ),
        migrations.AddField(
            model_name='kpd',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.unit'),
        ),
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('occupation', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.position'),
        ),
        migrations.AddField(
            model_name='employment',
            name='sbu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.sbu_directorate'),
        ),
        migrations.AddField(
            model_name='employment',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.station'),
        ),
        migrations.AddField(
            model_name='employment',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.unit'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='sbu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.sbu_directorate'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=15)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employment')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('first_in', models.TimeField()),
                ('last_out', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT'), ('UNAVAILABLE', 'UNAVAILABLE')], max_length=15)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.employee')),
            ],
        ),
    ]
